"""add expected_keywords and remark to interface_test_cases

Revision ID: 3642a0735cac
Revises: 7c24f77864e3
Create Date: 2026-04-02 15:52:48.471506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3642a0735cac'
down_revision: Union[str, None] = '7c24f77864e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface_test_cases', sa.Column('expected_keywords', sa.String(length=512), nullable=True))
    op.add_column('interface_test_cases', sa.Column('remark', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface_test_cases', 'remark')
    op.drop_column('interface_test_cases', 'expected_keywords')
    # ### end Alembic commands ###
