"""init all tables

Revision ID: 7c24f77864e3
Revises: 
Create Date: 2026-04-02 15:23:16.949003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c24f77864e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_templates_is_active'), 'skill_templates', ['is_active'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('is_active', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='http_method'), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('auth_type', sa.Enum('none', 'bearer', 'basic', 'apikey', name='auth_type'), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('is_enabled', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_category'), 'interfaces', ['category'], unique=False)
    op.create_index(op.f('ix_interfaces_created_by'), 'interfaces', ['created_by'], unique=False)
    op.create_index(op.f('ix_interfaces_is_enabled'), 'interfaces', ['is_enabled'], unique=False)
    op.create_table('interface_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('request_method', sa.String(length=16), nullable=False),
    sa.Column('request_url', sa.String(length=1024), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.SmallInteger(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.SmallInteger(), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interface_logs_created_at'), 'interface_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_interface_logs_interface_id'), 'interface_logs', ['interface_id'], unique=False)
    op.create_index(op.f('ix_interface_logs_is_success'), 'interface_logs', ['is_success'], unique=False)
    op.create_table('interface_test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('expected_status', sa.SmallInteger(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_result', sa.Enum('pass', 'fail', 'error', name='test_run_result'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interface_test_cases_interface_id'), 'interface_test_cases', ['interface_id'], unique=False)
    op.create_table('skill_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('skill_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', name='skill_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['skill_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_records_interface_id'), 'skill_records', ['interface_id'], unique=False)
    op.create_index(op.f('ix_skill_records_status'), 'skill_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_records_status'), table_name='skill_records')
    op.drop_index(op.f('ix_skill_records_interface_id'), table_name='skill_records')
    op.drop_table('skill_records')
    op.drop_index(op.f('ix_interface_test_cases_interface_id'), table_name='interface_test_cases')
    op.drop_table('interface_test_cases')
    op.drop_index(op.f('ix_interface_logs_is_success'), table_name='interface_logs')
    op.drop_index(op.f('ix_interface_logs_interface_id'), table_name='interface_logs')
    op.drop_index(op.f('ix_interface_logs_created_at'), table_name='interface_logs')
    op.drop_table('interface_logs')
    op.drop_index(op.f('ix_interfaces_is_enabled'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_created_by'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_category'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_table('users')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_skill_templates_is_active'), table_name='skill_templates')
    op.drop_table('skill_templates')
    # ### end Alembic commands ###
